from . import person
from . import patient
from . import patient_diagnosis
from . import doctor
from . import doctor_specialty
from . import disease
from . import disease_type
from . import patient_contact_person
from . import doctor_appointment
from . import doctor_personal_doctor_history
from . import medical_test
from . import medical_test_type
from . import sample
from . import sample_type
